
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 27 15:40:29 CEST 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 4;
  public static final int NOT_EQUAL = 35;
  public static final int SEMI = 44;
  public static final int GREATER = 38;
  public static final int LPAREN = 21;
  public static final int CONTINUE = 5;
  public static final int ASSIGN_DIV = 32;
  public static final int LESS = 39;
  public static final int FOR = 8;
  public static final int STATIC = 15;
  public static final int RPAREN = 22;
  public static final int AND = 43;
  public static final int OR = 42;
  public static final int BOOL = 47;
  public static final int COMMA = 45;
  public static final int ASSIGN_MUL = 31;
  public static final int CLASS = 3;
  public static final int INC = 41;
  public static final int ASSIGN_ADD = 29;
  public static final int DIV = 26;
  public static final int LESS_EQUAL = 37;
  public static final int ASSIGN_MOD = 33;
  public static final int ASSIGN = 28;
  public static final int IF = 9;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 34;
  public static final int GREATER_EQUAL = 36;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int ADD = 23;
  public static final int NUMBER = 49;
  public static final int MOD = 27;
  public static final int IDENT = 50;
  public static final int BREAK = 2;
  public static final int VOID = 16;
  public static final int LBRACK = 19;
  public static final int LBRACE = 17;
  public static final int ELSE = 6;
  public static final int READ = 13;
  public static final int RBRACK = 20;
  public static final int ASSIGN_SUB = 30;
  public static final int RBRACE = 18;
  public static final int EXTENDS = 7;
  public static final int PROG = 12;
  public static final int DEC = 40;
  public static final int SUB = 24;
  public static final int PRINT = 11;
}

